from graphviz_dot_hooks.utils import _rendered_contents_similar
from graphviz_dot_hooks.utils import _clean_rendered_content


def test_clean_rendered_content_svg_removes_generated_comment_():
    SAMPLE_CONTENT = """\n<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"\n "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n<!-- Generated by graphviz version 2.43.0 (0)\n -->\n<!-- Title: G Pages: 1 -->\n"""

    CLEANED = """\n<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"\n "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n<!-- Title: G Pages: 1 -->\n"""
    svg_content = SAMPLE_CONTENT.encode("utf-8")
    cleaned = _clean_rendered_content(svg_content, format="svg")
    assert b"<!-- Generated by graphviz version" not in cleaned

    # Normalize whitespace for comparison
    def norm(x):
        return b"\n".join(line.lstrip() for line in x.splitlines() if line.strip())

    assert norm(cleaned) == norm(CLEANED.encode("utf-8"))
    assert b"<!-- Title: G Pages: 1 -->" in cleaned


def test_clean_rendered_content_svg_removes_generated_comment():
    svg_content = (
        "<!-- Generated by graphviz version 2.43.0 (0)\n -->\n" "<svg>...</svg>"
    ).encode("utf-8")
    cleaned = _clean_rendered_content(svg_content, format="svg")
    assert b"<!-- Generated by graphviz version" not in cleaned
    assert cleaned.startswith(b"<svg>")


def test_clean_rendered_content_svg_no_comment():
    svg_content = b"<svg>...</svg>"
    cleaned = _clean_rendered_content(svg_content, format="svg")
    assert cleaned == svg_content


def test_clean_rendered_content_other_format():
    content = b"some binary or text content"
    cleaned = _clean_rendered_content(content, format="png")
    assert cleaned == content


def test__rendered_contents_similar__svg_with_different_versions_in_comment__marked_as_similar():
    content1 = (
        "<!-- Generated by graphviz version 2.43.0 (0)\n -->\n" "<svg>...</svg>"
    ).encode("utf-8")
    content2 = (
        "<!-- Generated by graphviz version 2.44.1 (1)\n -->\n" "<svg>...</svg>"
    ).encode("utf-8")
    assert _rendered_contents_similar(content1, content2, format="svg")


def test__rendered_contents_similar__svg_with_same_versions_in_comment__marked_as_similar():
    content1 = (
        "<!-- Generated by graphviz version 2.43.0 (0)\n -->\n" "<svg>...</svg>"
    ).encode("utf-8")
    content2 = (
        "<!-- Generated by graphviz version 2.43.0 (0)\n -->\n" "<svg>...</svg>"
    ).encode("utf-8")
    assert _rendered_contents_similar(content1, content2, format="svg")


def test__rendered_contents_similar__svg_with_same_versions_but_differences_in_svg__marked_as_different():
    content1 = (
        "<!-- Generated by graphviz version 2.43.0 (0)\n -->\n" "<svg>...</svg>"
    ).encode("utf-8")
    content2 = (
        "<!-- Generated by graphviz version 2.43.0 (0)\n -->\n" "<svg><more>...</svg>"
    ).encode("utf-8")
    assert not _rendered_contents_similar(content1, content2, format="svg")
