- id: check-dot
  name: check dot
  description: checks dot files for parseable syntax.
  entry: check-dot
  language: python
  files: '.dot$'
  pass_filenames: true
- id: render-dot
  name: render dot
  description: render all .dot to .dot.png
  entry: render-dot
  language: python
  files: '.dot$'
  pass_filenames: true
