# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks

fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: trailing-whitespace
        types: [python]
    -   id: end-of-file-fixer
        types: [python]

-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        name: flake8-blocking
        args: [ '--isolated', '--select=P,F401,F821,F901', '--ignore=P101,P102' ]
        additional_dependencies:
            - flake8-string-format

-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black