import os.path
import shutil
from subprocess import CalledProcessError
from typing import Optional
import tempfile
import re

from graphviz import render


def read_file(p: str) -> Optional[bytes]:
    if not os.path.exists(p):
        return None

    with open(p, "rb") as fin:
        return fin.read()


def _clean_rendered_content(content: Optional[bytes], *, format: str) -> bytes:
    """
    Clean the rendered content for a given format.
    e.g. For SVG, remove the comment line like <!-- Generated by graphviz version ... -->
    For other formats, return content unchanged.
    """
    if format == "svg":
        # Remove all comments that start with <!-- Generated by graphviz version ... -->
        # This is usually the first line in the SVG output
        content_str = content.decode("utf-8")
        cleaned_str = re.sub(
            r"<!-- Generated by graphviz version [^>]*-->\n?", "", content_str, count=1
        )
        return cleaned_str.encode("utf-8")
    return content


def _rendered_contents_similar(
    content1: Optional[bytes], content2: Optional[bytes], *, format: str
) -> bool:
    if content1 is None or content2 is None:
        return content1 == content2
    cleaned1 = _clean_rendered_content(content1, format=format)
    cleaned2 = _clean_rendered_content(content2, format=format)
    return cleaned1 == cleaned2


def _render_dotfile(
    src_dot_filepath: str, target_filepath: str, format: str
) -> tuple[bool, Optional[str]]:
    assert format in ("png", "svg")
    with tempfile.NamedTemporaryFile(suffix=f".{format}") as tmpf:
        try:
            print(f"rendering {src_dot_filepath} to {format}")
            render("dot", format, src_dot_filepath, outfile=tmpf.name)

        except CalledProcessError as ex:
            return False, str(ex)

        else:
            new_file_content = read_file(tmpf.name)
            old_file_content = read_file(target_filepath)

            if not _rendered_contents_similar(
                new_file_content, old_file_content, format=format
            ):
                print(f"Overwriting {target_filepath}")
                shutil.copy(tmpf.name, target_filepath)
                return False, f"Re-generated file {target_filepath}"
            else:
                print(f"{target_filepath} is up to date")
                return True, None


def render_dotfiles(
    dot_filepaths_map: dict[str, str], format: str
) -> tuple[bool, list[str]]:
    assert format in ("png", "svg")

    all_succeeded = True
    messages = []

    for src_dot_filepath, target_filepath in dot_filepaths_map.items():
        is_ok, error_message = _render_dotfile(
            src_dot_filepath=src_dot_filepath,
            target_filepath=target_filepath,
            format=format,
        )
        if not is_ok:
            messages.append(error_message)
            all_succeeded = all_succeeded and False

    return all_succeeded, messages


def _default_target_path(dot_filepath, format: str):
    return dot_filepath + f".{format}"


def _parse_only_convert(convert: str, format: str) -> dict[str, str]:
    convert_items = convert.split(",")

    convert_map = {}
    for convert_item in convert_items:
        src_target = convert_item.split(":")
        if not len(src_target) <= 2:
            raise ValueError(f"Wrong format of value for --only: {convert_item}")

        src = src_target[0]
        target = (
            src_target[1]
            if len(src_target) == 2
            else _default_target_path(src, format=format)
        )
        convert_map[src.strip()] = target.strip()
    return convert_map
